### ISSUE TITLE
Frameline Manager is not working with RH profiles

### ISSUE THREAD

**Issue by cvgaviao** [oddtopus/flamingo#13]
I added a RH section profile and then opened the Frameline Manager tool. I choose the RH profile and then the path and clicked in the "Redraw" button. 
The structure objects are being created but I can't see them.

I'm adding a project showing the issue: 
[failureFrame.zip](https://github.com/oddtopus/flamingo/files/2026827/failureFrame.zip)

**Comment by cvgaviao** [comment]
@oddtopus, could you please give me a feedback?

**Comment by oddtopus** [comment]
@cvgaviao ,
the reason is that the Arch function that it's used to create the square tubes profiles makes an inconsistent geometry. Practically the profile is generated by the subtraction of 2 rectangles, but the bigger is subtracted from the smaller, I guess.
Unfortunately this happened also for other profiles in the past.
The only workaround I have up to now is to delete the Section_RH.csv table and use a self-made profile <from Sketch>, using the dialog of frameBranch.
