### ISSUE TITLE
Screenshots and installation instructions

### ISSUE THREAD

**Issue by luzpaz** [oddtopus/flamingo#3]
Please add to README.md for better comprehension. Thx!

**Comment by luzpaz** [comment]
Also a link back to the freecad forums where users can seek support etc...

**Comment by luzpaz** [comment]
Also add a description summary to the github repo

**Comment by luzpaz** [comment]
Please also tag this repo with the 'freecad' tag

**Comment by oddtopus** [comment]
@luzpaz pong :-)
I saw your ping in my mailbox. Sorry for the late reply but I've been busy lately.
Since May I already modified a bit the README file so I can't just merge yours. Anyway I downloaded the raw file and will add the links you suggest in my next commits.

BTW, I think you also mentioned something about using Arch-axis objects. Can you give me more reference or advices (examples, documentation..) about Arch-axis class structure and usage? I think I could use them for the frameLine object in flamingo WB.

Thanks

**Comment by luzpaz** [comment]
@oddtopus Arch-axis see #4 

Another topic: would it be OK to rename https://www.freecadweb.org/wiki/Sandbox:Flamingo to https://www.freecadweb.org/wiki/Flamingo ?

**Comment by luzpaz** [comment]
@oddtopus please add a description summary to the github repo
